GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Mark Gaus",
    "email": "guos@email.com",
    "street" : "10 Vienna strasse",
    "city" :  "Vienna",
    "zipCode":  321113,
    "tasks": [{ "id": 1, "title": "Find electriv fields", "completed" : false }],
    "posts": [{ "id": 1, "title": "post", "body": "I like electricity" }]
}

###
//Get By id
GET http://localhost:3000/users/60913131aa9cb7fd675e2c6f

###
PUT http://localhost:3000/users/609ec15692f7efd53ed27b7e
Content-Type: application/json

{
    "name": "Moni Motek",
    "email": "yoni@email.com",
    "street" : "10 haim",
    "city" :  "netanya",
    "zipCode":  32323,
    "tasks": [{ "id": 1, "title": "Yoni should do somthing long", "completed" : true },{ "id": 2, "title": "Yoni is about to buy a house", "completed" : false},{ "id": 3, "title": "Yoni should do somthing", "completed" : false }],
    "posts": [{ "id": 1, "title": "post", "body": "yonis post body" }]
}

###
DELETE  http://localhost:3000/users/60913229aa9cb7fd675e2ce3
